import numpy as np

def direct_to_carte(str_file):
    with open(str_file, 'r') as data:
        fl = data.readlines()

        scale_factor = float(fl[1])

        lattice_matrix = scale_factor*np.array([list(map(float, i.split())) for i in fl[2:5]]).T
        frac_coord_matrix = np.array([list(map(float, j.split())) for j in fl[8:]]).T
        carte_coord_matrix = np.dot(lattice_matrix, frac_coord_matrix).T

    with open('poscar_carte.vasp', 'w') as output:
        output.write('generated by sampad' +'\n')
        for k in fl[1:7]:
            output.write(k)

        output.write('Cartesian'+'\n')
        for l in carte_coord_matrix:
            output.write('\t'+"{:.16f}".format(l[0])+'\t'+"{:.16f}".format(l[1])+'\t'+"{:.16f}".format(l[2])+'\n')

    return carte_coord_matrix

structure_file = input('Enter the POSCAR format file with fractional coordinates\n')
direct_to_carte(structure_file)
